# Generated by Django 5.0 on 2023-12-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(verbose_name='id')),
                ('book_name', models.CharField(max_length=150, verbose_name='name')),
                ('author_id', models.IntegerField(verbose_name='author_id')),
                ('copies_count', models.IntegerField(verbose_name='copies_count')),
            ],
        ),
    ]
